trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

stages:

- stage: TerraformPlan
  displayName: "Terraform Plan"
  jobs:
  - job: Plan
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'terraform-sp'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'tfstatekaustav123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'terraform-sp'
        commandOptions: '-var-file=terraform.tfvars'