trigger:
- main

pool:
  name: Default   # uses your self-hosted agent

variables:
  TF_VAR_resource_group_name: Terraform_RG
  TF_VAR_location: centralindia
  TF_VAR_vm_size: Standard_DC4s_v3
  TF_VAR_admin_password: $(ADMIN_PASSWORD)
  TF_VAR_subscription_id: $(AZURE_SUBSCRIPTION_ID)

steps:
- script: |
    echo "Running on self-hosted agent"
    uname -a
  displayName: "Verify Agent"

# Login to Azure using CLI (runs on your machine)
- script: |
    az login
  displayName: "Azure Login (Manual)"

# Terraform Init
- script: |
    terraform init -input=false
  displayName: "Terraform Init"

# Terraform Plan
- script: |
    terraform plan -input=false
  displayName: "Terraform Plan"
