trigger:
- main

pool:
  name: Default

variables:
- group: terraform-vars

steps:
- script: |
    echo "Checking environment"
    which terraform
    which az
  displayName: "Debug Environment"

- script: terraform init -input=false -upgrade
  displayName: "Terraform Init"

- script: terraform plan -input=false
  displayName: "Terraform Plan"
  env:
    TF_VAR_subscription_id: $(AZURE_SUBSCRIPTION_ID)
    TF_VAR_admin_password: $(ADMIN_PASSWORD)